extends: airbnb-base 
plugins:
  - import
rules:
  # TODO: Remove this when we have shifted away from the async package
  no-shadow: 'warn'
  # Gulpfiles and tests use dev dependencies
  import/no-extraneous-dependencies: ['error', { devDependencies: ['gulpfile.babel.js', 'gulp/**/**.js', 'test/**/**.js']}]
